- src/components/SignUpLink.js
Fixes issue #2 
Adds a bit of margin between the date select dropdown and the signup button
> Fix date select dropdown spacing

- CONTRIBUTING.md
#16 Created a basic CONTRIBUTING file. Included URLs to the project website, as well as to the LICENSE page.
Let me know if you would like me to add/delete anything, and thank you!
> Create CONTRIBUTING page

- README.md
> Move copyright out of code block

- CONTRIBUTING.md
- src/CovidAppointmentTable.js
- src/components/MoreInformation.js
Deffo needs re-design but will do for now.
> add restrictions for non-state sites

- CONTRIBUTING.md
- src/App.js
@livgust this is what I could get done tonight on getting the filters into the responsive drawer. The button to open the drawer in mobile mode is still a little ugly but i think all the functionality and other styling is there. I won't be able to touch this until tomorrow night so go ahead and merge this into your version of this branch and take it up tomorrow if you have time.
I also merged some more changes from develop
> Put filters into a responsive drawer

- .circleci/config.yml
- README.md
If you want to do this, you'll need to do the following.  I'm happy to do this if you give me privs.
1. link your github account to circle-ci.
2. setup the project by clicking on circle-ci
You may also want to tweak the node version in the config.yml to match prod.
> Setting up circleci automation to do build and test

- src/CovidAppointmentTable.js
Not 100% sure if we want the "above" or "following".
> Fixed merge error

- src/components/Availability.js
- src/components/Availability.test.js
- src/components/MoreInformation.js
- src/components/MoreInformation.test.js
closes #62 
shows totalAvailability if availability not present/filled out
fix to More Information if address not available
> Updates for cvs

- src/CovidAppointmentTable.js
- src/components/SignUpLink.js
Fixes #67
Only shows locations that has a sign up button.
This filters out locations that have a positive number of available slots, but doesn't have any sign up link for the user.
> Filter changed to only show those locations that have a sign up link.

- src/CovidAppointmentTable.js
- src/components/StaleDataIndicator.js
Filters out any data that is older than "tooStaleMinutes" which is currently set at "60" (1 hour)
Fixes #60
> Filters out old data

- README.md
Added instructions for unit testing code prior to committing changes.
> README: Added section on unit testing

- src/CovidAppointmentTable.js
- src/CovidAppointmentTable.test.js
Fixed #79 
Refactored NoAppointmentsAlert
Added real UI for the ErrorMessageAlert
replaced previous check for an 'alert' role in the error message
> Refactored NoAppointmentsAlert

- package-lock.json
- package.json
- src/CovidAppointmentTable.js
- src/components/FilterPanel.js
- src/services/appointmentData.service.js
Filters out all of the stale data immediately at the transformData call.
FYI. This reduced the data set from 132 entries to 95.
> Filters out "too stale" data immediately

- src/App.js
- src/CovidAppointmentTable.js
In preparation for tomorrow's rush, let's get an alert ready to push.
> add alert for March 4

- src/CovidAppointmentTable.js
> chore: run prettier

- package-lock.json
- package.json
- src/CovidAppointmentTable.js
- src/components/Availability.js
- src/components/Availability.test.js
Accepts "m/d/y" or "YYYY-MM-DD" from the backend.
Transforms both to "ddd MMM D" (For example, Tue Mar 2) for UI.
Uses 'dayjs' for date operations
> Parses multiple date formats.

- src/components/Availability.js
- src/components/StaleDataIndicator.test.js
- src/setupTests.js
- src/translations/translations.en.main.json
Using i18next for "slot" vs "slots".
> I18next slots

- .gitignore
- .prettierrc.json
- package-lock.json
- package.json
- public/index.html
- src/App.js
- src/App.test.js
- src/CovidAppointmentTable.js
- src/components/FilterPanel.js
- src/components/HelpDialog.js
- src/components/Menu.js
- src/components/MoreInformation.js
- src/components/StaleDataIndicator.test.js
- src/services/appointmentData.service.js
This is mostly a test to see if this is automatically assigned to Zach or how the reviewing process works.
This is a merge of what's in develop now, but via merge commits, because they made the merge work so much more easily.
Not fully tested by me so may not be ready to go. 
cc @harcod @tkjones117
> Merge develop into master, with Rob's sort-zipcode

- README.md
> Doc: Update instructions on how to run Prettier

- src/components/StateEligibility.js
3 related but independent enhancements for StateEligibility.js:
* Refactor to editable strings/array/object
* Use PeopleIcon instead of CheckIcon
* Update teachers' URL
> StateEligiblity.js: Eligibility string enhancements

- src/components/Availability.js
- src/components/Availability.test.js
Fixes #99 
Wrote all new tests to provide full code coverage of `Availability.js`
> Unit Tests: Availability.test.js

- src/App.js
- src/components/FilterPanel.js
Fixed margin for "Update List" button on mobile.
Changed icon on "Filter Locations" button.
**AFTER:**
**BEFORE:**
> Filter Panel: UI button margin and icon.

- src/components/FilterPanel.js
Apparently during a recent cleanup merge I ran
HUSKY=0 git rebase -i @~5
and somehow missed a whitespace error, and failed to re-run the test before pushing.
I am ashamed.
> FilterPanel.js: Prettier

- src/components/StateEligibility.js
> Update StateEligibility.js: Remove console.log

- src/App.test.js
- src/components/AlertBanner.js
- src/components/FilterPanel/index.js
- src/components/Menu.js
Site Banner & Menu>Resources
(and for some reason I could commit code because of 'jest' FAILS.
Fixed one. Skipped the other.
> Preregistration Banner

- .circleci/config.yml
- .husky/pre-commit
- README.md
- package-lock.json
- package.json
Similar to https://github.com/livgust/covid-vaccine-scrapers/pull/140/ on the scrapers project but uses circle ci + husky instead.
> Verify lockfile

- src/App.js
The wrong key was being used for sorting.
> Fixed "no ZIP Code" sort

- .prettierignore
- src/App.test.js
- src/CovidAppointmentTable.js
- src/components/FilterPanel/AvailabilityFilter.js
- src/components/FilterPanel/RadiusFilter.js
- src/components/FilterPanel/index.js
- src/components/StateEligibility.js
- src/services/appointmentData.service.js
- test/fixtures/api/no-data.json
- test/fixtures/api/prod.json
Closes #142
**Test**: "when the api endpoint can not be reached"
**Before**: Was failing because there are multiple "role=alert" on the screen when the site's AlertBanner is displayed.
**Now**: This test checks for the existence of "Unexpected Internal Error" which is the title of the ErrorMessageAlert
> No longer skips test

- src/components/StateEligibility.js
New vaccination eligibility dates.
> New state eligibility dates

- src/components/Availability.js
- src/components/Availability.test.js
- src/components/MoreInformation.js
Closes #154 
Updated text and removed the HelpDialog completely since all of the information is displayed on the page.
**NOW**
**BEFORE**
> Updated "no date-specific" messaging.

- src/App.test.js
- src/components/FilterPanel/index.js
Renaming buttons for clarity. 
Before:
After:
https://macovidvaccines.slack.com/archives/C01N7C2G2KF/p1616772120071800
> rename filter buttons

- src/App.js
- src/CovidAppointmentTable.js
- src/services/appointmentData.service.js
> Distance Filter Too Restrictive

- src/CovidAppointmentTable.js
Marshfield Fairgrounds & Amherst Bangs Community Center were recently added to the preregistration system.
> New MassVax Locations added

- public/index.html
- src/components/FilterPanel/RadiusFilter.js
- src/components/NotificationsDialog.js
added 2 mi and 5 mi radius to notification choices
> Notifications: Smaller Radius Choices

- src/components/Availability.js
UX [Discussion on Slack](https://macovidvaccines.slack.com/archives/C01N7C2G2KF/p1619365660205300)
We've reached a moment when there are frequently appointments available today. This PR highlights slots that are available **today**.
> Highlight today's availability

- package-lock.json
- package.json
- src/About.js
- src/Router.js
- src/components/Availability.js
- src/components/Copyright.js
- src/index.js
- src/translations/translations.en.main.json
There is one route "/about" that shows a prototype for an About Us page.  There is no direct navigation to this page in this PR.
"/" shows the current site <App />
"/about" shows the prototype for an About Us page. <About />
every other route redirects to "/" (otherwise we would get a 404 error).
> Basic React Router installation

- src/About.js
- src/App.js
- src/CovidAppointmentTable.js
- src/components/Availability.js
- src/components/Availability.test.js
- src/components/Copyright.js
- src/components/FilterPanel/AvailabilityFilter.js
- src/components/FilterPanel/RadiusFilter.js
- src/components/FilterPanel/ZipCodeFilter.js
- src/components/FilterPanel/index.js
- src/components/HelpDialog.js
- src/components/Menu.js
- src/components/MoreInformation.js
- src/components/NotificationsDialog.js
- src/components/PhoneNumber/index.js
- src/components/SignUpLink.js
- src/components/StaleDataIndicator.js
- src/components/StaleDataIndicator.test.js
- src/translations/translations.en.main.json
`translations/translation.en.main.json` is the English translation file.
> Extracted hard coded strings for translation
