- src/components/Availability.js
- src/components/HelpDialog.js
- src/components/SignUpLink.js
https://github.com/livgust/macovidvaccines.com/issues/7
HelpDialog component includes help icon that you click to see dialog and "OK" button in dialog for closing (also closes if you click outside).
Used to provide additional context in two cases:
- No date-specific data available
- No sign-up link available
> Add HelpDialog component to give context on availability

- src/components/Menu.js
Link to mass.gov/covidvaccine gives a security warning becuase the state didn't redirect properly. 
Link changed to a non-redirecting link.
> Menu>Resources: Link to mass.gov/covidvaccine gives a security warning

- src/CovidAppointmentTable.js
- src/components/HelpDialog.js
If we see text suggesting a site is only open to residents of a certain area, we will show an icon with hover text:
When clicked, it will show a dialog with more context.
Also slightly refactors the HelpDialog component; make sure that still works (click a ? icon and make sure it shows a Dialog)
Future-proofing: if `data` passes in a "restrictions" item, will use that to as source-of-truth instead of doing a regex against More Information (state-sponsored sites only).
ALSO I changed the default sort to alphabetical based on user feeback.
> Add warning when sites are restricted

- src/CovidAppointmentTable.js
Tighen up the regexp matching.
Don't trigger on /resident/, which improperly matches on both Fenway
and Foxborough as they have this text now:
...
and residents and staff of public and private low-income and
affordable senior housing
Instead, trigger on either /County residents/ or /eligible residents/,
to cover this case:
This clinic is for eligible Franklin County residents under phase 1
and:
These clinics are for eligible residents under the Massachusetts
> Don't show restriction for mass sites (Foxborough, Fenway)

- src/CovidAppointmentTable.js
Unconflicted version of #39, which was inadvertently closed.
Format the restriction box to put the information that users need to see first, and don't format it a hard-to-read light grey.
It looks like that formatting is an error in how HelpDialog is implemented, but I'm not sure.
Other changes worth doing but not implemented here would be: 1) tightening up the space after the heading, 2) copying the yellow/amber iconography into the dialog, 3) formatting the OK button with an affordance for clicking. I'm sure someone more experienced in React could do those much faster than I.
**Before**:
**After**:
>  Restriction box detailing

- src/CovidAppointmentTable.js
- src/components/StaleDataIndicator.js
- src/components/StaleDataIndicator.test.js
approved UX by Daniel
when more than 8 minutes old, shows timestamp (X:XX AM/PM)
when yesterday, shows yesterday
when older than yesterday, shows date (we should arguably filter these out though, I'll make a new issue)
> Stale data indicator

- src/components/HelpDialog.js
- src/components/Menu.js
Console shows validateDOMNesting warnings when you open the About/Resources menu options, or when you open the "This site may be restricted" HelpDialogs in the appointment table. This PR addresses that.
Thanks!
> Clean up validateDOMNesting console warnings

- src/components/StateEligibility.js
This morning there was a press conference update from Baker: https://www.wcvb.com/article/teachers-press-baker-to-offer-covid-19-vaccine-after-biden-directs-states-to-vaccinate-educators/35706923
I'm updating the eligibility section to note March 11 educator eligibility.
Before: 
After: 
Will make a ticket to remove this on March 11 (integrate the educator eligibility into the normal section).
> add March 11 eligibility note

- src/App.js
- src/components/FilterPanel.js
_@livgust wrote in a previous review:_
> I was only able to look a little bit but I noticed 2 things:
> 
> 1. clicking the "Has Available Appointments" checkbox is REALLY slow. I think part of it is because (left a comment above) whenever it's clicked we're also re-filtering out stale entries. That's added computation we don't need.
> 2. If you deselect "Has Available Appointments" and then resize the window such that the display changes (if the side bar was docked before, now it's not, or vice versa) when you open the filters again the checkbox is checked even though you deselected it. The state of the checkbox should refer to the same React Hook ("useState" variable) regardless of visuals.
> 
> I'm not sure how much you're planning on addressing within this PR so let me know if you want …
> Synced checkboxes in both FilterPanels.

- src/components/StaleDataIndicator.test.js
That is, time (+11 mod 12 ) +1, because +11+1 = 12 = 0 mod 12.
Use some variables (consts) for clarity, this is a little too much
math for template literals.
Please note this fix only is needed between 12:00 and 12:59pm
> StaleDataIndicatorTest.js: 1-12, not 0-11

- src/components/FilterPanel.js
The  `us-Zips` library is based on ZCTAs (ZIP Code Tabulation Areas) and does not contain every ZIP Code.  Basically, just ZIP Codes with populations attached.  This commonly excludes PO Box zip codes and "unique" ZIP Codes like 12345.  I think that USPS probably just mapped 12345 as unused because of the common pattern and just assigned to Schenectady, NY because they other 123xx codes.
Code was updated to use the default "location sort order" if the ZIP code is invalid or doesn't have coordinates.  It was previously defaulting to the last computation at reported in Issue #118
> Invalid (or Unknown) ZIP Codes sort by location.

- src/CovidAppointmentTable.js
- src/components/MoreInformation.js
- src/components/StaleDataIndicator.js
There have been a number of items suggested in the #ux channel.  This PR address a few of them.
1. Keep the city near the location
2. There was no space separating MA and ZIP Code in MoreInformation.... was ",MA01760".  Now ",MA 01760"
3. Changed the size of the "stale icon" to match the "restriction icon"
4. Changed "**Important Eligibility Notice**" to "**Information about eligibility**" as recommended in the [#ux channel by Daniel](https://macovidvaccines.slack.com/archives/C01N7C2G2KF/p1614795429083700)
**BEFORE:**
**AFTER:** _(the data wasn't stale on the 2nd screen shot! The icon is the same size as the restriction)_
> UX: LocationCard visual changes

- src/components/StateEligibility.js
React wants all list text to be in a <ListItemText>.
If not, you can get weird resizing effects on iPhones, among other things.
> StateEligibility.js: Use ListItemText!

- src/App.js
- src/components/AlertBanner.js
Created a separate component for the site banner.  This alert appears at the top of the site (usually on Thursday mornings).
This should eliminate having to deal with merge conflicts on App.js when we are just changing the banner text.
Fixes a spacing issue with css that was previously accomplished with a "<br />" after the alert
Added new functionality:
**startDate** and **endDate** so we can have the alert appear and vanish at predetermined intervals.  There is a sample alert from last week that is commented out in the file.
> Refactor AlertBanner out of App.js

- src/components/AlertBanner.js
- src/components/StateEligibility.js
Fixes [much of] #142.
`<Alert/>`s are siblings requiring a `key`. This is probably going to be
true anytime we produce React elements with .map(), I guess. Get used to it?
`<CriterionItem/>`s are now also such siblings, so their `<ListItem/>`
children no longer are. Move the key to the former, and eliminate
passing the extra `index` to CriterionItem().
> AlertBanner,StateEligibility: Correct React key warnings

- src/components/StateEligibility.js
This automatically updates to the correct eligible listing on the appropriate dates through April 19, 2021 when everyone over the age of 16 becomes eligible.
**Today (March 17th)**
**On Monday, March 22, 2021**
_(Note: This subsumes "65 and older" into "60 and older")_
**On Monday, April 5, 2021**
_(Note: This subsumes "60 and older" into "55 and older", and "two or more conditions" into "one or more")_
**On Monday, April 19, 2021**
_(Note: Just one category here -- EVERYONE)_
> Eligibility schedule for all remaining dates

- src/components/MoreInformation.js
There was no space between the state and the ZIP Code because of the new line in the code.
17 Corinth St, Roslindale, MA 02131 (was 17 Corinth St, Roslindale, MA02131)
> Missing space in addresses

- src/services/appointmentData.service.js
We're seeing Walgreens with 1 or 2 appointments that are more than 20 minutes stale, those are not bookable.
Continue to tweak this as time goes on.
> fast-fix: Drop tooStale filter from 60 minutes to 20 minutes

- src/components/Availability.js
- src/components/Availability.test.js
- src/components/SignUpLink.js
- src/services/appointmentData.service.js
Fixes #174 The incoming JSON file might send appointmentData in an unsorted order.
All of the keys are now converted to a sortable format "YYYY-MM-DDTHH:mm:ssZ".  The keys are then sorted.
Formatting is left until the time of display in Availability.js and SignUpLink.js
This input data with out-of-sequence dates:
```
"availability": {
"4/8/2021": {
"numberAvailableAppointments": 13,
"hasAvailability": true
},
"4/10/2021": {
"numberAvailableAppointments": 32,
"hasAvailability": true
},
"4/6/2021": {
"numberAvailableAppointments": 27,
"hasAvailability": true
},
"4/7/2021": {
"numberAvailableAppointments": 35,
"hasAvailability": true
}
},
```
Now produces:
> Sort the appointment dates

- src/services/appointmentData.service.js
Fixes #172 
BaystateHealth, HeywoodHealthcare, and CVS ( in the past ) are returning `totalAvailability` when they can detemine the number of appointments, but not on which day the appointments are on.
Here is a devtest.json file that produces the following location card.
```
{
"version": 1,
"timestamp": "2021-03-12T130557Z",
"results": [
{
"name": "Heywood Healthcare",
"street": "171 Kendall Pond W",
"city": "Gardner",
"state": "MA",
"zip": "01440",
"signUpLink": "https://gardnervaccinations.as.me/schedule.php",
"hasAvailability": true,
"totalAvailability": 12,
"timestamp": "2021-03-12T13:05:57.896Z",
"latitude": 42.5864159,
"longitude": -71.9870586
}
]
}
```
> Read 'totalAvailability' from json

- src/CovidAppointmentTable.js
Fixed #181 
Several additional locations have been added to the Preregistration System recently.  This number currently stands at 7 MassVax sites plus 6 regional collaboratives. The state's site says that "_More locations will continue to be added_."
The text was updated to be more generic so that additional updates to this site will not be necessary as the Commonwealth adds more sites.
In addition, the button was redirected to the state's information page rather than directly sending the user to the registration page.
> MassVax card updated

- src/App.js
- src/Router.js
Allows for specific ZIP Codes to be specified in the URL.  This would enable local government or news websites to publish a link to MACovidVaccines.com with a targeted _ZIP Code_.  Currently, the default when visiting the site with the plain URL ( https://MACovidVaccines.com ) is to show all locations with available appointments **sorted alphabetically** by the location's name.
For example, Worcester, MA could use the direct URL:
https://MACovidVaccines.com/zip/01601
> URL Route for ZIP Codes

- src/App.js
1. Invalid ZIP Codes are ignored
2. If cookie exists, then it is updated
3. If cookie doesn't exists, then the parameter is used as the "default" ZIP Code.
> FAST FIX: ZIP Code parameter cases handled

- src/components/Availability.js
- src/translations/translations.en.main.json
I chose 7 dates because that would be a week's worth of everyday appointments.  If the user is looking for an appointment on a Saturday and _one exists_, then it is guaranteed to be in the list.
This is what we show prior to this PR...
> Truncate long lists of dates

- src/About.js
- src/App.test.js
- src/CovidAppointmentTable.js
- src/components/Menu.js
- src/translations/translations.en.main.json
The Commonwealth has opened MassVax sites to immediate public appointments.
There is still some `massVax` code remaining, but I left it there since it might be needed to handle historical data that is floating around in the database.
> Remove all Preregistration messaging
